---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(p8105.datasets)
library(viridis)
library(plotly)

data("nyc_airbnb")

# data cleaning
nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    borough = neighbourhood_group, neighbourhood, rating, price, room_type, lat, long
    ) |>
  drop_na(rating)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
borough_vec = nyc_airbnb |> pull(borough) |> unique()

selectInput(
  inputId = "borough_choice",
  label = h3("Select Borough"),
  choices = borough_vec,
  selected = "Manhattan"
)

sliderInput(
  inputId = "price_range",
  label = h3("Select a price range"),
  min = 50, max = 1000,
  value = c(100, 400)
)

room_choice = nyc_airbnb |> distinct(room_type) |> pull()
# radioButtons widget
radioButtons(
  "room_choice", 
  label = h3("Choose room type"),
  choices = room_choice, selected = "Entire home/apt")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({ 
  nyc_airbnb |>
  filter(
    borough == input[["borough_choice"]],
    price < input[["price_range"]][2], price > input[["price_range"]][1],
    room_type == input[["room_choice"]]
  ) |> 
    plot_ly(x = ~long, y = ~lat, type = "scatter", mode = "markers", color = ~price)
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderText({
  input[["price_range"]]
})
```

### Chart C

```{r}

```

